In [1]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [2]:
y_predicted =np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [12]:
def MAE(y_true,y_predicted):
    total_error = 0
    for yt,yp in zip(y_true,y_predicted):
        print(yt,yp)
        total_error += abs(yt - yp)
    print('Total error: ',total_error)
    mae = total_error / len(y_true)
    return print('MAE:',mae)

In [13]:
MAE(y_true,y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1
Total error:  2.5
MAE: 0.5


In [17]:
np.mean(np.abs(y_predicted - y_true)) # same as the whole function

0.5

# Log Loss Function

In [18]:
eplison = 1e-15 # something close to 0

In [19]:
y_predicted # want to convert 0 to something to near 0 and 1 to something near 1

array([1, 1, 0, 0, 1])

In [22]:
y_predicted_new = [max(i,eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [23]:
y_predicted_new = [min(i,1-eplison) for i in y_predicted_new]
y_predicted_new
# we do this becuase log(0) is undefined

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [24]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [25]:
np.log(y_predicted) # see it gives inf , bad for trainning

C:\Users\musta\AppData\Local\Temp\ipykernel_10188\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [26]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844